import Header from "@/components/custom/Header";
import { getServerSession } from "next-auth";
import { Toaster } from "react-hot-toast";
import { authOptions } from "../api/auth/[...nextauth]/route";
import SignInPage from "../sign-in/page";
  

export const metadata = {
  title: 'Create UI',
  description: 'Generated by Next.js',
}

export default async function DashbordLayout({ children }) {
  const session = await getServerSession(authOptions);

  if (!session) {
    return <SignInPage />;
  } else {
    return (
      <div className=" w-full relative  max-lg:px-4  pt-[80px] px-10 ">
        <Toaster />
        <Header />
        {children}
      </div>
    );
  }
}
