import React from 'react'
import SignIn from '../../components/custom/SignIn'
import { authOptions } from '../api/auth/[...nextauth]/route';
import { getServerSession } from 'next-auth';
 export const metadata = {
    title: 'Sign-In',
    description: 'Generated by Next.js',
  }
async function SignInPage() {
  const session = await getServerSession(authOptions); 
 
     
    return (
    <>
    <div className=' flex flex-col items-center bg-[white] justify-center h-screen w-full'>
       <div className=' logo text-[170px] max-[362px]:text-[39px] mb-10 max-lg:text-[60px] font-bold text-[#CBACF9] '>
         Blured UI. 
        <span className=' text-sm bg-indigo-400 text-white font-normal px-2 ml-2 rounded'>Beta</span>
      </div>
      <SignIn  session={session}/>
    </div>
    </>
  )
   
}

export default SignInPage