import { authOptions } from '@/app/api/auth/[...nextauth]/route';
import CodeForm from '@/components/custom/CodeForm'
import { getCode } from '@/lib/actions/codeSave'
import { getServerSession } from 'next-auth';
import React from 'react'
export const metadata = {
  title: 'Update UI Code',
  description: 'Generated by Next.js',
}
async function page({params}) {

  
  const title = await getCode({title:params?.id})
  const session = await getServerSession(authOptions);
  return (
    <div>
        <CodeForm head={'Update'}  title={title} owner={session?.user?.email} />
    </div>
  )
}

export default page